#!/bin/bash

echo "=== Google Cloud Speech-to-Text Actual Usage ==="
echo ""
echo "Your project: gen-lang-client-0047710702"
echo ""

echo "To see your ACTUAL usage and costs:"
echo "=================================="
echo ""
echo "1. Open Google Cloud Console:"
echo "   https://console.cloud.google.com/billing"
echo ""
echo "2. Select your billing account"
echo ""
echo "3. Go to 'Reports' in the left menu"
echo ""
echo "4. Filter by:"
echo "   - Service: 'Cloud Speech-to-Text API'"
echo "   - Time range: 'This month' or 'Custom range'"
echo ""
echo "5. You'll see:"
echo "   - Exact minutes/hours used"
echo "   - Daily breakdown"
echo "   - Actual costs incurred"
echo ""

echo "Alternative: Check API & Services Dashboard"
echo "=========================================="
echo "1. Go to: https://console.cloud.google.com/apis/api/speech.googleapis.com/metrics?project=gen-lang-client-0047710702"
echo ""
echo "2. Look at 'Traffic by API method' chart"
echo "3. Check 'StreamingRecognize' requests"
echo ""

echo "Cost Estimate Based on Your $20 Spend:"
echo "====================================="
echo "- $20 = 1,111 billable minutes (after 60 free)"
echo "- Total usage: 1,171 minutes (19.5 hours)"
echo ""
echo "This seems like the service was left running overnight."
echo ""

echo "Quick Math:"
echo "==========="
echo "If you started using it yesterday and it ran until now:"
yesterday=$(date -v -1d "+%B %d")
today=$(date "+%B %d")
echo "- Started: $yesterday"
echo "- Current: $today"
echo "- That's about 24 hours of potential runtime"
echo ""
echo "19.5 hours of usage fits if you started late yesterday"
echo "and it ran through the night until this morning."